name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: runscript
      id: runscript
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: runscript
        setup-command: ''
        command: python3 test.py
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUNSCRIPT_RESULTS: "${{steps.runscript.outputs.result}}"
      with:
        runners: runscript
